### PR TITLE
Fix the AddData Intent

### LINKED ISSUE #293: Cannot add data through shortcuts integration
# Defectus Demonstrandum

As reported on the forum: https://forum.beeminder.com/t/ios-shortcut-integration/10024

Attempting to run a shortcut which adds data to beeminder produces the error: “Could not run Add Data - There was a problem communicating with the app”.

# Nota Nebulosa

iOS Logs show:
```
[__extensionPrincipalClass conformsToProtocol:@protocol(NSExtensionRequestHandling)] - /Library/Caches/com.apple.xbs/Sources/ExtensionFoundation/ExtensionFoundation/Source/NSExtension/NSExtensionSupport/EXConcreteExtensionContextVendor.m:109: NSExtensionPrincipalClass does not conform to NSExtensionRequestHandling protocol!
```

This looks plausibly related.

### PR DESCRIPTION
**Pull request by theospears**
Previous commits had begun to implement an intent to add data points to beeminder. This follows up on that work, adding the necessary extension routing and parameter checking to make intents support work without launching the app. This should be seen as a minimum viable implementation, there remain many possible improvements to e.g. error handling, and suggesting allowed goal names.

As datapoint submission is now handled the the extension this removes the code which submitted them as part of app startup.

Fixes #293

Test Plan:
* [X] Created a shortcut which added a data point
* [X] Ran this shortcut, observed it finished successfully and that the data point was added
* [X] Tried to run without a goal name set, or with an invalid goal name, and observed a sensible error.

### CODE REVIEW

File: BeeSwift/AddDataIntentHandler.swift [hunk 1]
```diff
@@ -12,28 +12,46 @@ import BeeKit
...
+        } else {
+            return INStringResolutionResult.needsValue()
+        }
     }
     
-    func confirm(intent: AddDataIntent,
-               completion: @escaping (AddDataIntentResponse) -> Void) {
-        completion(AddDataIntentResponse(code: .ready, userActivity: nil))
+    func confirm(intent: AddDataIntent) async -> AddDataIntentResponse {
+        if intent.goal != nil && intent.value != nil {
```
Comment (krugerk) [inline BeeSwift/AddDataIntentHandler.swift:33]: How about an extension with computed property `isValid`?

File: BeeSwift/AppDelegate.swift [hunk 2]
```diff
@@ -153,22 +153,16 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterD
     func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
         if #available(iOS 12.0, *) {
```
Comment (krugerk) [inline BeeSwift/AppDelegate.swift:154]: While here, how about turning this line into a `guard`?

File: BeeSwiftIntents/IntentHandler.swift [hunk 3]
```diff
@@ -0,0 +1,17 @@
+//
+//  IntentHandler.swift
+//  BeeSwiftIntents
+//
+//  Created by Theo Spears on 9/1/22.
+//  Copyright © 2022 APB. All rights reserved.
```
Comment (krugerk) [inline BeeSwiftIntents/IntentHandler.swift:6]: Is this still accurate? Code you type is Copyright _andrewpbrett_ ?

File: BeeSwiftIntents/IntentHandler.swift [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+//
+
+import Foundation
+import Intents
+
+@available(iOS 14.0, *)
+class IntentHandler : INExtension {
+    override func handler(for intent: INIntent) -> Any? {
+        return AddDataIntentHandler()
```
Comment (krugerk) [inline BeeSwiftIntents/IntentHandler.swift:15]: [redundantReturn](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantreturn)

File: BeeSwift/AddDataIntentHandler.swift [hunk 5]
```diff
@@ -12,28 +12,46 @@ import BeeKit
...
+        }
     }
 
     func handle(intent: AddDataIntent,
               completion: @escaping (AddDataIntentResponse) -> Void) {
-        guard let datapointValue = intent.value else { return }
-        
-        RequestManager.addDatapoint(urtext: "^ \(datapointValue)", slug: intent.goal!) { (response) in
-            completion(AddDataIntentResponse.success(goal: intent.goal!))
+        guard let goal = intent.goal else {
```
Comment (krugerk) [inline BeeSwift/AddDataIntentHandler.swift:42]: How about naming this variable `goalSlug` or `slug`? It is not a full JSONGoal but merely a String containing the goal's slug.

File: BeeSwiftIntents/IntentHandler.swift (hunk 3 above)
Comment (theospears) [reply BeeSwiftIntents/IntentHandler.swift:6]: I think my preference would be to strip all of these comment headers - copyright on opensource files with multiple contributors ends up pretty complex, and all the other info in the headers is redundant.

File: BeeSwift/AddDataIntentHandler.swift (hunk 5 above)
Comment (theospears) [reply BeeSwift/AddDataIntentHandler.swift:42]: This seems reasonable. In a perfect world we would rename the property on the Intent to `goalSlug` and then do `guard let goalSlug = intent.goalSlug ...`. However, given the intent already exists, renaming the property would break existing shortcuts which I'm reluctant to do.

This means the best we can get to is `guard let goalSlug = intent.goal ...` - trading off a better name for less consistency. So not a costless win, but maybe still net better?

File: BeeSwift/AppDelegate.swift (hunk 2 above)
Comment (theospears) [reply BeeSwift/AppDelegate.swift:154]: I don't think this behaves quite like a guard, because we still want to inspect `userActivity.userInfo?` later even if it's not satisfied?

Comment (krugerk) [reply BeeSwift/AppDelegate.swift:154]: Of course the function will need to return something when running on lower than ios 12. The guard's else provides for this.

The meat of the function though happens inside that if and using a `guard` here should allow one to compose much more legible code.

See https://github.com/raywenderlich/swift-style-guide#golden-path

File: BeeSwift/AddDataIntentHandler.swift (hunk 5 above)
Comment (krugerk) [reply BeeSwift/AddDataIntentHandler.swift:42]: Here I only meant the new code which introduced the `guard let goal = ...` variable. That local variable might better named slug.
